### ISSUE TITLE
关于 AIFLoggerConfiguration

### ISSUE THREAD

**Issue by czwen** [casatwy/RTNetworking#12]
hi  @casatwy 
请问，AIFLoggerConfiguration.m 的作用是什么？AIFLoggerConfiguration.m 里面的变量，赋值之后好像就没使用了。AIFLogger 带上传log 功能吗？
我想将 RTNetworking 改造成可移植的库。

**Comment by casatwy** [comment]
AIFLogger不带上传Log的功能。

AIFLogger的Configuration其实是当初安居客的配置单，我拎出RTNetworking的时候，把业务相关的东西都去掉了。

由于不同的公司或组织实现API的方式不一样，因此将RTNetworking改造成可移植的库其实非常困难。
