### ISSUE TITLE
HTTPS 

### ISSUE THREAD

**Issue by Wu-Dong-Hui** [casatwy/RTNetworking#17]
casa大神，如果在现有基础上支持HTTPS，有什么思路可以参考的？

**Comment by casatwy** [comment]
?????????af??????????????????????

???? iPhone

? 2016?8?30??15:27?Roy <notifications@github.com<mailto:notifications@github.com>> ???

casa?????????????HTTPS????????????

##

**Comment by Wu-Dong-Hui** [comment]
what???

![image](https://cloud.githubusercontent.com/assets/8233494/18082643/66b4582c-6ed2-11e6-9ef0-69f424198710.png)

**Comment by casatwy** [comment]
诶？我手机回复的竟然是乱码？

这个HTTPS其实是在AFNetworking里面做的，基本上不需要额外动。
