### ISSUE TITLE
可否在ViewController补充上一些调用api的代码呢？

### ISSUE THREAD

**Issue by 03128crz** [casatwy/RTNetworking#2]
我屏蔽了AIFServiceFactory相关的import代码，可以运行，现在想在
controller试着调用api，发现无从下手，谢谢～

**Comment by casatwy** [comment]
从BaseAPIManager派生一个你自己的Manager出来，然后设置好methodName，service等帮助组装URL的参数，然后实例化这个manager，设置好delegate等，就可以通过[self.manager loadData]的方式调用了。

ppt里面也有相关的使用方法可以参考哈。

**Comment by 03128crz** [comment]
看了ppt，总算能正确运行了，谢谢哦
