### ISSUE TITLE
一个controller中多个请求

### ISSUE THREAD

**Issue by Wu-Dong-Hui** [casatwy/RTNetworking#20]
casa，一个controller中多个请求的情况，APIManager参数和回调的代理方法中除了使用if-else来判断属于哪个请求，还有什么更优雅的方式吗？
![image](https://cloud.githubusercontent.com/assets/8233494/19584129/b8fdbf72-9774-11e6-9c90-0bf955b789f3.png)

**Comment by casatwy** [comment]
如果不是代码问题，就去评论区提问，我一定会回答。issue里面只回答demo本身的bug问题。

**Comment by Wu-Dong-Hui** [comment]
sorry

**Comment by casatwy** [comment]
如果不是代码问题，就去评论区提问，我一定会回答。issue里面只回答demo本身的bug问题。

发自我的 iPhone

在 2016年10月21日，09:59，Roy <notifications@github.com<mailto:notifications@github.com>> 写道：

casa，一个controller中多个请求的情况，APIManager参数和回调的代理方法中除了使用if-else来判断属于哪个请求，还有什么更优雅的方式吗？
[image]https://cloud.githubusercontent.com/assets/8233494/19584129/b8fdbf72-9774-11e6-9c90-0bf955b789f3.png
