### ISSUE TITLE
Why not pack as a pod?

### ISSUE THREAD

**Issue by DamianSheldon** [casatwy/RTNetworking#21]
It seems that the content of section of Adding CTNetworking to your project is empty in README.Why no pack as a pod just as early version, so it can be used directly without adding source files or modifying implement of some method. Can we through some configure methods or other means archive the same effect, I consider these ways better than add source file to framework or modify implement of some method in framework.

**Comment by casatwy** [comment]
因为有很多弱业务的东西如果抽出来了，其实就增加了代码的复杂度，不值得。而且每家公司有每家公司不同的需求，应该自己维护自己的网络库，否则限制就很大，而且补丁代码会污染整个工程。
