### ISSUE TITLE
请求错误返回status 0

### ISSUE THREAD

**Issue by Batxent** [casatwy/RTNetworking#22]
在使用该网络库请求的时候，某一个请求总是返回status 0 ,
Error Domain Code:			        -999
Error Localized Description:			已取消

**Comment by casatwy** [comment]
复现步骤是什么？请求内容是什么？

发自我的 iPhone

在 2016年11月8日，19:07，Batxent <notifications@github.com<mailto:notifications@github.com>> 写道：

在使用该网络库请求的时候，某一个请求总是返回status 0 ,
Error Domain Code: -999
Error Localized Description: 已取消

―

**Comment by Batxent** [comment]
只是设置了 HTTPHeaderField，没有params。我单独开了个工程直接用AF去请求，返回是正确的。用CTNetworking是走到dataTaskWithRequest 这个方法，在里面返回了error

**Comment by casatwy** [comment]
你能把你的测试代码提给我么？我好追进去看一下调用栈

**Comment by casatwy** [comment]
刚刚有人也提了个类似的issue，最后找到原因是因为manager没有被strong住，你可以看看是不是也是这个原因？

相关issue：https://github.com/casatwy/RTNetworking/issues/23

**Comment by Batxent** [comment]
manager 确实是被viewController strong 住的，是不是这个原因：在请求还未完成的时候viewController被释放了（因为跳转到下个页面等等原因），导致manager 被释放从而 cancel了请求，这种情况该怎么解决？

**Comment by casatwy** [comment]
这种情况被取消，难道不是正常的么？

**Comment by Batxent** [comment]
有些请求并不希望它随着页面的消失而取消掉，这种情况应该也是有的吧。

**Comment by casatwy** [comment]
网络请求发出去了之后，客户端做的取消其实就只是不响应delegate了而已，或者队列中的请求不发送而已。

如果你需要确保拿到请求回调或者确保队列中的请求也能发送，那么就把这个API Manager挂到全局单例上去。

不过这种情况极少。
