### ISSUE TITLE
Error Domain=NSURLErrorDomain Code=-999 "cancelled" 

### ISSUE THREAD

**Issue by joywt** [casatwy/RTNetworking#23]
运行一个 https 请求总遇到 Error Domain=NSURLErrorDomain Code=-999 "cancelled"  搜了下资料说是sessionManager 提前被释放了，但是看了代码 sessionManager 并没有被释放，那么逐行排查到
CTApiProxy 代码 139 行 self.dispatchTable[requestId] = dataTask;  

把这行代码注销了就能正常返回。请教下 casatwy 是什么原因？

**Comment by casatwy** [comment]
能提交一个testcase作为pr给我么？我好去查到底是什么问题～

发自我的 iPhone

在 2016年11月17日，19:57，joywt <notifications@github.com<mailto:notifications@github.com>> 写道：

运行一个 https 请求总遇到 Error Domain=NSURLErrorDomain Code=-999 "cancelled" 搜了下资料说是sessionManager 提前被释放了，但是看了代码 sessionManager 并没有被释放，那么逐行排查到
CTApiProxy 代码 139 行 self.dispatchTable[requestId] = dataTask;

把这行代码注销了就能正常返回。请教下 casatwy 是什么原因？

**Comment by joywt** [comment]
找到问题了。manager 没有被 controller 持有，所以 loadData 后就会执行父类的 dealloc 方法，改请求就被取消了。
`- (void)loadHomePageData{
    TestManager *manager =  [[TestManager alloc] init];
    [manager setDelegate:self];
    [manager setParamSource:self];
    [manager loadData];
}
`
