### ISSUE TITLE
 post 请求应删除  request.HTTPBody 赋值

### ISSUE THREAD

**Issue by joywt** [casatwy/RTNetworking#24]
CTRequestGenerator  第 84 行

`NSMutableURLRequest *request = [self.httpRequestSerializer requestWithMethod:@"PUT" URLString:urlString parameters:requestParams error:NULL];
    request.HTTPBody = [NSJSONSerialization dataWithJSONObject:requestParams options:0 error:NULL];`

第二行代码给 HTTPBody 的值是未经格式化的字典类型 requestParams ,并且覆盖了第一行代码给  HTTPBody 的值，正确的应该是 key=value&key2=value2

**Comment by casatwy** [comment]
这个不一定的，取决于服务端怎么读，尤其是在Content-Type是application/json的情况下，给到的就应该是json数据。

发自我的 iPhone

在 2016年11月17日，20:04，joywt <notifications@github.com<mailto:notifications@github.com>> 写道：

CTRequestGenerator 第 84 行

NSMutableURLRequest *request = [self.httpRequestSerializer requestWithMethod:@"PUT" URLString:urlString parameters:requestParams error:NULL]; request.HTTPBody = [NSJSONSerialization dataWithJSONObject:requestParams options:0 error:NULL];

第二行代码给 HTTPBody 的值是未经格式化的字典类型 requestParams ,并且覆盖了第一行代码给 HTTPBody 的值，正确的应该是 key=value&key2=value2

―
