### ISSUE TITLE
疑问

### ISSUE THREAD

**Issue by LionBuer** [casatwy/RTNetworking#28]
一个请求对应一个apiManager ?

**Comment by casatwy** [comment]
是的

**Comment by LionBuer** [comment]
有点不明白CTService和CTServiceFactory的作用和使用场景,方便解释一下吗?我的理解应该只会有一个CTService吧

**Comment by casatwy** [comment]
如果你要引入第三方API，或者你们公司有很多个团队提供API，那么就会有不止一个service
