### ISSUE TITLE
AIFServiceProtocal 声明的属性为何要单独出来，不放在AIFService中？

### ISSUE THREAD

**Issue by 03128crz** [casatwy/RTNetworking#3]

**Comment by casatwy** [comment]
因为有一个request工厂，它在生产request的时候只关心publicKey，工厂的操作对象的facade也只是AIFService，而不是AIFService< AIFServiceProtocal>。

然后，只有子类才关心onlinePublicKey和offlinePublicKey，所以子类需要实现AIFServiceProtocal，出于要限制子类继承的目的，给出了这个protocol来当子类的禁锢。

如果protocol不单独拎出来，放到基类AIFService里面的话，基类表达的数据就不单纯了，也起不到对子类的禁锢作用了。

**Comment by 03128crz** [comment]
看来需要细细理解，谢谢大牛 :)

**Comment by 03128crz** [comment]
看来需要细细理解，谢谢大牛 :)
