### ISSUE TITLE
如何优雅的在成功回调方法区分是刷新还是加载？

### ISSUE THREAD

**Issue by slemon** [casatwy/RTNetworking#30]
你好，很喜欢你的网络层架构的思路，所以按照你的方法自己写了一个，因为项目较小所以做了些精简，基本的思想还是用delegate代替block，然后每个接口用一个apiManager集成自baseApiMananger，对数据还是采用了datamodle的形式，但遇到一个问题 ，loaddata 和 loadnextpage 返回都会调用 - (void)managerCallAPIDidSuccess:(CTAPIBaseManager *)manager 方法，那如何区分是刷新还是下载下一页呢？通过 manager 的response 里面的数据去区分是个好方法吗？

**Comment by casatwy** [comment]
调用loadData是刷新，调用loadNextPage是下一页。所以只要看调用哪个方法就可以了

**Comment by slemon** [comment]
我的问题其实是loadData 和  loadNextPage 最终都会回调- managerCallAPIDidSuccess方法，那么ni s 如何在managerCallAPIDidSuccess中区分回调是loadData 还是 loadNextPage 产生呢？ 应用场景，比如加载一个tableivew 列表，加载下一页是是往datalist里面 appenddata，如果是刷新先要把datalist里面的 data 全部remove掉

**Comment by casatwy** [comment]
看当前的pageNumber，第一页肯定是loadData

发自我的 iPhone

在 2017年7月16日，上午9:41，Lemon Sun <notifications@github.com<mailto:notifications@github.com>> 写道：


我的问题其实是loadData 和 loadNextPage 最终都会回调- managerCallAPIDidSuccess方法，那么ni s 如何在managerCallAPIDidSuccess中区分回调是loadData 还是 loadNextPage 产生呢？ 应用场景，比如加载一个tableivew 列表，加载下一页是是往datalist里面 appenddata，如果是刷新先要把datalist里面的 data 全部remove掉
