### ISSUE TITLE
服务器返回的数据reformer的问题

### ISSUE THREAD

**Issue by xiongbingyang** [casatwy/RTNetworking#31]
您好，麻烦问一下，对于服务器返回的数据，如果是下面的图片这样的：
![image](https://user-images.githubusercontent.com/14078005/28361446-60a3cc2e-6cab-11e7-8c6e-e04615230523.png)
那这个怎么去model化啊，这个name在使用的时候肯定被当作是NSString的对象，但是如果服务器返回是上图那样的数据的话，取出来是一个 NSNull 的对象，被当作NSString 的对象去使用就会有问题。
这个如果在回调的数据那里校验的话，层级如果太深，而且回来的数据是NSString对象的太多了，感觉会写很多校验的代码。但是如果转model的话，转model的框架就会对这个进行处理了。想问一下对于这个情况casa是怎么处理的啊？

**Comment by casatwy** [comment]
用reformer处理各种边界情况呀

**Comment by xiongbingyang** [comment]
- (NSDictionary *)reformData:(NSDictionary *)originData fromManager:(APIManager *)manager；意思是在这个方法中把所有可能出错的数据都取出来去做处理？

**Comment by casatwy** [comment]
是的，reformer给出的结果就应该符合“无错”、“直接可用”这两个条件

**Comment by xiongbingyang** [comment]
那这样的话，像服务器如果返回的数据层级太深或者需要判断的数据特别多，那也得依次取出来查看是否是正确的数据，感觉这工作量也太大了啊。

**Comment by casatwy** [comment]
第一，就算你不在reformer里面判，那使用的地方也需要判啊。

第二，使用的地方需要什么你就取什么就好啦，为什么要返回完整的数据呢？

**Comment by xiongbingyang** [comment]
第一，如果不用Model的话确实是需要判断的，我现在的问题就是如果不用Model有没有比较好的方法不去处理这个，因为毕竟如果用了Model的话，三方库会去处理这种NSNull的情况。然后reformer里面依然往使用者传递的是Model的数据。

第二，这个情况只是举一个例子，就是假如很多数据返回的刚好是NSNull的这种类型而且也是使用者需要使用的数据，意思不是说要返回完整的数据。

**Comment by casatwy** [comment]
1. 那你就写一个工具去获取数据咯，然后判nil、NSNull的事情就让这个工具去做呀

2. 同1

**Comment by xiongbingyang** [comment]
嗯，好的。谢谢 casa ！
