### ISSUE TITLE
关于shouldCallBackByFailedOnCallingAPI的参数

### ISSUE THREAD

**Issue by dylanGao** [casatwy/RTNetworking#32]
GDMapService.m中的shouldCallBackByFailedOnCallingAPI方法总
// token 无效，重新登录
        [[NSNotificationCenter defaultCenter] postNotificationName:kBSUserTokenIllegalNotification
                                                            object:nil
                                                          userInfo:@{
                                                                     kBSUserTokenNotificationUserInfoKeyRequestToContinue:[response.request mutableCopy],
                                                                     kBSUserTokenNotificationUserInfoKeyManagerToContinue:self
                                                                     }];
此处kBSUserTokenNotificationUserInfoKeyManagerToContinue:对应self，这块self是service，
是不是应该是manager？或者service中有办法可以获得manager？

**Comment by casatwy** [comment]
确实，这边的应该是Manager～
