### ISSUE TITLE
CTAPIManagerValidator为什么没声明获取最后验证错误信息的方法？

### ISSUE THREAD

**Issue by DamianSheldon** [casatwy/RTNetworking#33]
由于 CTAPIManagerValidator 没声明获取最后验证错误信息的方法，所以在 CTAPIBaseManager 的方法里只能笼统地返回CTAPIManagerErrorTypeParamsError。有看到 CTAPIBaseManager 声明只读的 errorMessage 属性，理论上子类覆盖为 readwirte, 然后 CTAPIManagerValidator 验证的时候把错误信息写到它里面也可以传递出来，但这个事情和 CTAPIManagerValidator 更紧密，为什么不直接在它里面声明个 readonly 的类似 lastError 的属性呢？

**Comment by casatwy** [comment]
validator只是个protocol，所以你在实现validator的时候，可以想怎么用就怎么用，想怎么声明就怎么声明。
