### ISSUE TITLE
Xcode Version 8.3.2 (8E2002) ios 10.3 第二次请求同一个api 报错处理

### ISSUE THREAD

**Issue by hongjinlin** [casatwy/RTNetworking#36]
场景：用户登录第一次登录失败，再次点击登录，会报如下错误。
[AFHTTPRequestSerializer requestWithMethod:URLString:parameters:error:]: message sent to deallocated instance 0x6080002ab8e0
解决方案：修改CTRequestGenerator.m
1、将第 22 行 改为 @property (nonatomic, weak) AFHTTPRequestSerializer *httpRequestSerializer;
2、将第 124 - 134 行注释去掉，再次运行问题得已解决。
问题原因我尚未分析清楚，有弄明白的哥们还请分享下。

**Comment by casatwy** [comment]
你现在可以先这么改着，我最近正在重构RTNetworking，以后RTNetworking就不会有request generator了

**Comment by hongjinlin** [comment]
好的，谢过大神！敢问要如大神一样成为出色架构师，可以推荐一些学习的书籍吗？感激不尽
