### ISSUE TITLE
调用RESTful API的时候怎么拼接参数

### ISSUE THREAD

**Issue by kingstal** [casatwy/RTNetworking#37]
您好，我现在在项目中使用CTNetworking进行接口调用，目前采取的还是传统的方式，调用方提供参数字典，将参数字典按键值对的形式拼接在`methodName`的后面用问号分隔作为`query`，组成完整的url。

现在项目改造，统一采用RESTful API，想请教一下这种情况下该怎么去构造url。

**Comment by casatwy** [comment]
在-methodname里面可以使用self.paramSource获取参数然后拼接

**Comment by kingstal** [comment]
在`-methodname`里调用`self.paramSource`获取参数拼接完后之后，是不是也应该在manager的`reformParams`方法中返回一个空字典，这样在最后生产request的时候才会是正确的request ？

**Comment by casatwy** [comment]
无所谓的，paramSource的内容是只会放入body的，你现在的做法就是再挂到URL上而已

**Comment by kingstal** [comment]
我debug看了一下，发送get请求的时候，是会把`-reformParams `方法返回的字典生成string作为query挂到URL后面的

**Comment by casatwy** [comment]
这个request generator里面你是可以随便改的

发自我的 iPhone

在 2017年9月22日，下午1:15，WangMinjun <notifications@github.com<mailto:notifications@github.com>> 写道：


我debug看了一下，发送get请求的时候，是会把-reformParams方法返回的字典生成string作为query挂到URL后面的

**Comment by kingstal** [comment]
好的，非常感谢，问题已经解决。
