### ISSUE TITLE
怎么支持分布式服务器

### ISSUE THREAD

**Issue by wwpeter** [casatwy/RTNetworking#38]
项目项目多个服务器支持

**Comment by casatwy** [comment]
分布式服务器对内是分布式，对外还是有统一入口的，这个事情按道理应该是服务端的人去做。

如果你们服务端的人水平不行，那就在Service提供baseUrl的地方由直接提供baseURL改为在url列表里面随机选一个提供。

**Comment by wwpeter** [comment]
- (NSString *)apiBaseUrl
{
    return self.child.isOnline ? self.child.onlineApiBaseUrl : self.child.offlineApiBaseUrl;
}

**Comment by wwpeter** [comment]
不太知道 ，怎么修改，自己写的 那个server，里面配置的url。但是对外 提供的3个代理是一样的啊， 怎么知道调用那个服务呢？

**Comment by wwpeter** [comment]
大佬，能不能教我一下， 万分感谢，不然我还要再用一个请求类了。

**Comment by casatwy** [comment]
我这个框架的关于URL生成的过程是这样的：

根据APIManager的service identifier去获得service，从而获取API的baseURL
根据APIManager的method name和base URL 拼成一个完整的URL
（GET请求）根据APIManager的paramsSouce获得参数，拼在URL之后

所以如果你要在前端去做分布式服务的话，那就在获取baseURL的地方做手脚。

CTService是所有Service的基类，你可以在子类中实现onlineApiBaseUrl方法或offlineApiBaseUrl方法。在这个方法里面你return的URL是从一个列表（可用的服务器列表）里面取出来的。

**Comment by wwpeter** [comment]
那也只能提供2个服务啊？是不是啊？感谢解答

**Comment by casatwy** [comment]
你先说一下你理解的分布式服务

**Comment by wwpeter** [comment]
GDMapService 这个类可以对应多个？ 我现在这个 就写了一个，

**Comment by casatwy** [comment]
？你这段话说完了？

可以对应多个什么？你就写了一个什么？

**Comment by wwpeter** [comment]
分布式，就是一个项目又对个服务器提供服务。 我让我们技术提供统一的入口了。之前写的不是统一个入口。

**Comment by casatwy** [comment]
你这里多个服务器提供服务，是指多个服务器针对同一个API提供服务，还是多个服务器针对项目中的多个业务一对一提供服务？

**Comment by wwpeter** [comment]
继承CTService的子类写了一个

**Comment by casatwy** [comment]
你这里多个服务器提供服务，是指多个服务器针对同一个API提供服务，还是多个服务器针对项目中的多个业务一对一提供服务？

**Comment by wwpeter** [comment]
不同的api，我们的存管放在别的服务器，登陆注册等等放在另一个服务器。

**Comment by wwpeter** [comment]
统一的域名的话，我就不用改了

**Comment by casatwy** [comment]
那就再创建一个新的service子类就好了，用它提供新的baseURL，指向你移出去的那台服务器。

然后对应APIManager里面把service identifier改成你这个新的identifier

最后在service factory中给出对应service identifier的service实例

**Comment by wwpeter** [comment]
咱们这个上传的数据是用- (NSDictionary *)paramsForAPI:(AZAPIBaseManager *)manager ，如果要在body里面上传json要怎么处理呢？
NSMutableURLRequest *request = [[NSMutableURLRequest alloc] initWithURL:[NSURL URLWithString:url]];
    [request setHTTPMethod:@"POST"];
    NSData *data = [jsonStr dataUsingEncoding:NSUTF8StringEncoding];
    [request setHTTPBody:data];

**Comment by wwpeter** [comment]
我问那个问题还是对您封装的这个没全部理解，现在知道那个URL怎么处理了。

**Comment by wwpeter** [comment]
大佬 ， 还在吗？我描述的这个问题，您有问题吗？

**Comment by wwpeter** [comment]
怎么这个是只能拼接在 ？后面，把上传的参数，没有提供把参数这样设置吧？
NSString *jsonStr = [self convertToJsonData:paramSourse];
 NSMutableURLRequest *request = [[NSMutableURLRequest alloc] initWithURL:[NSURL URLWithString:url]];
   [request setHTTPMethod:@"POST"];
    NSData *data = [jsonStr dataUsingEncoding:NSUTF8StringEncoding];
    [request setHTTPBody:data];

**Comment by wwpeter** [comment]
咱们这个是只能拼接在 ？后面，把上传的参数，没有提供把参数这样设置吧？
NSString *jsonStr = [self convertToJsonData:paramSourse];
NSMutableURLRequest *request = [[NSMutableURLRequest alloc] initWithURL:[NSURL URLWithString:url]];
[request setHTTPMethod:@"POST"];
NSData *data = [jsonStr dataUsingEncoding:NSUTF8StringEncoding];
[request setHTTPBody:data];

**Comment by casatwy** [comment]
body里面上传json的话，就setdata的时候，用NSJSONSerialization生成的data就好了啊

**Comment by casatwy** [comment]
拼接在？后面的是GET请求，拼接在body里面的一般都是POST请求

这要看你这个API具体是哪个method了

**Comment by wwpeter** [comment]
[request setHTTPBody:data];  这一种的怎么添加啊？大佬

**Comment by casatwy** [comment]
照着你们API的规范来啊，如果你们API要求json，那就给json的data，如果要求form，那就给form的data啊，HTTP也有规范的，搜一下就有了。

**Comment by wwpeter** [comment]
这样写的您这个框架就不能使用了，

**Comment by casatwy** [comment]
…

要不这样，你先研究一下http规范？

**Comment by wwpeter** [comment]
- (NSDictionary *)paramsForAPI:(AZAPIBaseManager *)manager，这里面的数据上传的数据form的data。
这里面怎么给json的data呢？
