### ISSUE TITLE
网络请求 不能正常的接受回调；Batch、Chain请求如何优雅的实现

### ISSUE THREAD

**Issue by bluesky0109** [casatwy/RTNetworking#39]
在gitter上提问请教但 没回复，也没找到 评论区在哪，只能在这个发个 issue，请教下 如下两个问题

`- (void)dealloc
{
    [self cancelAllRequests];
    self.requestIdList = nil;
}`

CTAPIBaseManager 这里的 dealloc,取消所有的请求 是否不太合理，这样就要求 调用的地方 必须持有 发起请求的 实例才能正常接受到 回调，理论上 请求是否被取消 不应该跟 发起者的生命周期强依赖；

2、网络请求 都用delegate的方式来处理回调，按照 .key里面的解释 确实带来的非常多的好处。 如果遇到 这两种场景：1：A、B、C、D 这个作为一组 Batch请求 ；2：A、B、C、D 这个作为一组后者依赖前者回调结束才发起 的 Chain请求，请教 该如何优雅的实现？

**Comment by bluesky0109** [comment]
@casatwy 能抽时间回复下👆的问题吗？ 谢谢

**Comment by kaynewbie** [comment]
1. 我觉得 ‘强引用 发起请求的实例’ 没什么问题；
2. 我开发中用了 RAC，每个请求都写成一个信号，然后串联多个信号执行，效果挺好的。

**Comment by kaynewbie** [comment]
delegate 好像不是很适合用串联执行信号🤣

**Comment by casatwy** [comment]
1. 我的设计是一个APIManager实例服务一个调用者，所以要求调用者强引用APIManager实例，这么做的好处就是每个调用者都能很精细地控制调用流程和周期。同时，这种做法不影响你做“不持有”的改造，你把APIManager做成单例就好。

如果不用这种方式，那么APIManager势必会被用来服务于多个调用者，这时候想要再进行精细控制，就不太现实了。而且也难以改造成可以被精细控制的方式，因为它天生就不受控制。

所以这两者怎么权衡，你明白了吧？

2 自己创建一个APICenter去管理A、B、C、D四个API。如果是batch，那么APICenter统一下令放飞请求。如果是串行，APICenter中持有一个strategy字典，在每一个APIManager回来的时候，走strategy决定下一个应该放飞哪个API，或者汇总数据返回出去。

**Comment by bluesky0109** [comment]
@casatwy 第二个问题的回答 能完全理解赞同。

第一个问题的回答中 ：同时，这种做法不影响你做“不持有”的改造，你把APIManager做成单例就好，这种 做单例虽然能解决，但是 很多场景下 调用者 可能并不需要 精细控制，为了 能正常 接受 回掉 做个单例 得不偿失，这种方案 虽能解决问题 但总觉得 不太合适，能从 APIManager本身设计上 找到更合适的方式解决吗？要不要 精细控制 及 要不要 强持有 应该交还给 调用者 自己根据场景决定

**Comment by casatwy** [comment]
我知道你想说用类方法的形式同时接收参数和回调block的方法去做。

这种做法放弃了paramSource对参数的管理和转化

放弃了validator对参数的验证和返回数据的验证（对返回数据的验证很重要，会影响缓存的正确执行）

放弃了精细控制（虽然有时候这个并不是必要的）

reformer对返回数据的转化倒是不受影响。

以上这些其实都还可以接受，只要你参数简单、数据简单。

但使用单例去做，比用类方法+block的方式的差别在于，单例没有改变原本的调用模式，不会引入异构。

引入异构会导致代码维护困难。举个例子，原来工程师们使用类方法+block的方式去调，后来有一天业务变化了，类方法+block要改成APIManager实例了，这时候的工作量就蛋疼了。

单例要看你怎么实现了，如果每个APIManager一个实例，那确实是要跪。

如果这个单例只是一个只返回API数据的APIManager工厂，每次调度API的时候动态生成APIManager，并自己hold住，然后调用，调用结束自己释放APIManager（高频API可建立缓存策略），并将数据返回，情况就会好得多。

毕竟我设计的APIManager的相关操作基本都是面向协议的，APIManager具体是什么类型，只要不涉及精细控制，其实都可以无所谓。

这样就不会引入异构，同时单例的危害也能减到最小。因为每次请求都有内存的开销，性能会慢一些，但这种增大的开销绝对不会成为瓶颈（最多因为内存申请的过程比原来多开销几百个纳秒乃至几毫秒？这都是可以忽略不计的。内存在调用完毕之后又回收了，单例工厂自己占用的内存能有几十个k？反正内存占用肯定不会过100k）

客户端跟服务端不一样，对性能的要求很低很低。服务端是锱铢必较，100ms跟110ms的差别很大，是10%的性能差别。客户端就无所谓了，用户完全感觉不到100ms和110ms的差别，即使存在10%的性能损耗，在他眼里这俩都叫一瞬间。

所以我选择单例。但我更多的时候，不会去考虑“不持有”的改造，因为即使现在没必要持有，等将来有必要持有的时候，改动就能最小。

而且由于我持有了这些API，我可以在打开代码的第一眼知道这个对象都调用了哪些API，这也是很棒的。

**Comment by bluesky0109** [comment]
@casatwy 感谢耐心解答🙏，我想的 最本质的 是不改变你原有设计的 精细控制，有没有 更优雅的 方式 从APIManager设计的本身 来去 让 调用者 持有和不持有都能正常接受 回调，其他的都保持不变；理论上 请求是否被取消 不应该跟 发起者的生命周期强依赖 同时这个也是我提这个的一个原因，只是想找到更优雅的解决方案

**Comment by casatwy** [comment]
@bluesky0109 

理论上 请求是否被取消 不应该跟 发起者的生命周期强依赖 

这个理论是不成立的。我可以举一个反例：

ViewController是hold住view的，在ViewController释放了之后，view也释放了。如果此时view正在进行渲染工作，那么这个工作就也跟着取消了。

如果你不希望这个view的渲染随着ViewController的释放而取消，那你就把view挂在window上。

---分割线---

一个对象是hold住APIManager的，在这个对象释放之后，APIManager也释放了。如果此时APIManager正在发起请求，那么这个请求也就跟着被取消了。

如果你不希望这个APIManager的请求随着对象的释放而取消，那你就把APIManager挂在APICenter或者别的什么对象上。

**Comment by bluesky0109** [comment]
@casatwy 你上面举例的场景确实对应你设计的初衷，我也举一个 场景：
比如 某个 页面 进入时 要后台 下载某个资源 然后存储在本地，便于再次进来可以直接使用， 这个页面释放时，如果下载没结束 并不希望取消这个 task；同时 这个 下载的task 页面也并不用关注持有 发起者，对于页面 只关注 2点，1、本地 是否有缓存、2、如果没有 就下载（也不关注 下载的结果 即不需精确控制）；这种也是 app应用 常有的场景需求。 如果需要 需取消 应该是调用者 通过 APIManager 对外开放的 cancel来 自己管理决定何时取消，不应该跟 发起者的 生命周期 强依赖

**Comment by casatwy** [comment]
这种场景需要有一个DownLoadManager来管理下载任务。然后DownloadManager去管理文件下载、断点续传、目录管理、缓存策略的事情。DownloadManager应当脱离具体的页面而存在。

APIManager在DownloadManager里面只为文件下载提供API调用服务，例如根据用户ID获取下载URL的列表这种。在我的设计里面，APIManager甚至都不是为了下载任务而设计的。

同时，在你的需求中，下载过程还需要提示进度，APIManager设计的初衷只是用于API的请求，下载进度用苹果原生的API就已经足够，AFNetworking也对下载做了很好的封装。

DownloadManager里面还需要进行文件目录管理、缓存策略，这两个你都需要有对应的FileManager，CacheManager来为DownloadManager服务。

如果你把这些事情都交给APIManager去做，反而是不合适的。APIManager只是为DownloadManager诸多需求中的其中一个来服务而已。

锤子只是设计用来钉钉子或者拔钉子的，可你想要拿它去拧螺丝，那就是你不对啦。这跟锤子没有关系，你不能怪锤子为什么不能拧螺丝。

**Comment by bluesky0109** [comment]
感谢解答。理解了 一些特殊需求 应该 单独 抽象 封装一层 来处理具体的业务逻辑，只是 底层 依赖 APIManager 或 AFN 等 其他所需 支持服务

**Comment by casatwy** [comment]
对的

**Comment by bluesky0109** [comment]
我能 基于 你这个 repo 进行 二次 修改调整 自用吗？ 某些 地方 各项目 具体需求 业务逻辑 不同

**Comment by casatwy** [comment]
可以，这个repo本身就只是一个demo，不是一个库
