### ISSUE TITLE
请问业务方Controller中有多个api要调用，回调中如何区分？

### ISSUE THREAD

**Issue by 03128crz** [casatwy/RTNetworking#4]
//我想到的是通过判断 manager中类名来处理，请问您那边是怎么处理的，谢谢～
-(NSDictionary *)paramsForApi:(RTAPIBaseManager *)manager
{
    if(manager isKindOfClass:[TribeChannelListAPIManager]){
        //没有参数
    }else{
        NSDictionary *paramer = @{@"channelId":@1,@"page":@1};
    }

```
return paramer;
```

}

**Comment by casatwy** [comment]
if manager == self.channelListApiManager

**Comment by 03128crz** [comment]
原谅我问了个低级问题。。。
