### ISSUE TITLE
CTAPIBaseManager里的 isLoading 为什么没有用？

### ISSUE THREAD

**Issue by weiguangmeng** [casatwy/RTNetworking#40]
CTAPIBaseManager里的 isLoading 没有用到，loadDataWithParams方法直接设置isLoading为YES，没有对isLoading进行判断，如果是取消外面飞着的请求，让新发起的请求起飞，但代码里没有cancel外面飞着的请求代码，这是为什么？

**Comment by casatwy** [comment]
因为你发出去的请求收不回来
