### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by flytov** [casatwy/RTNetworking#46]
0 CoreFoundation | ___exceptionPreprocess + 228
-- | --
1 libobjc.A.dylib | objc_exception_throw + 56
2 CFNetwork | -[__NSCFURLLocalSessionConnection _tick_initialize]
3 AFNetworking | __93-[AFURLSessionManager dataTaskWithRequest:uploadProgress:downloadProgress:completionHandler:]_block_invoke + 60
4 AFNetworking | url_session_manager_create_task_safely + 96
5 AFNetworking | -[AFURLSessionManager dataTaskWithRequest:uploadProgress:downloadProgress:completionHandler:] + 216
6 FlexibleAIFNetworking | -[AIFApiProxy callApiWithRequest:progress:success:fail:] + 340
7 FlexibleAIFNetworking | -[AIFApiProxy callGETWithParams:serviceIdentifier:methodName:fileName:additionalHTTPHeader:progress:success:fail:] + 328
8 FlexibleAIFNetworking | -[RTAPIBaseManager loadDataWithParams:] + 2104
9 FlexibleAIFNetworking | -[RTAPIBaseManager loadData] + 100

**Comment by casatwy** [comment]
可以去CTNetworking的readme中参考一下Marvel API SDK或高德API SDK的实现。RTNetworking已经废弃不用了。
