### ISSUE TITLE
-(NSDictionary *)paramsForApi:(RTAPIBaseManager *)manager方法的意义？

### ISSUE THREAD

**Issue by 03128crz** [casatwy/RTNetworking#5]
为何不在调用api时直接传递请求的参数，而要额外写多一个方法去获取代理的参数呢？这样写有什么考虑，谢谢

**Comment by casatwy** [comment]
这个在PPT里面有哈，主要是为了防止代码散落各地。原来是两种传参方式都提供的，后来就只提供一种了。

另外，建议问题在评论区问哈。

**Comment by 03128crz** [comment]
好的，谢谢
