### ISSUE TITLE
RTAPIBaseManager 错误处理

### ISSUE THREAD

**Issue by iOkay** [casatwy/RTNetworking#9]
Components/Components/RTAPIBaseManager.m该文件中的failedOnCallingAPI:withErrorType:方法，是不是应该修改fetchedRawData。有时fetchedRawData会持有成功时的数据。

**Comment by casatwy** [comment]
我觉得没必要在这里删fetchedRawData

因为请求失败跟清除上一次请求的数据没有必然联系。如果有业务需求需要保留上一次的请求数据，在这里做数据清空就会导致混乱。

如果你的业务需求要求清空，那么就可以在拦截方法里面自行调用cleanData去清空数据。
